version: '3.8'

services:

  ashudb:
    image: mysql # docker image 
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: # env var for mysql root password setting 
      MYSQL_ROOT_PASSWORD: Cisco077

  ashuwebapp:
    image: adminer # docker image 
    restart: always
    depends_on: # web app need db container to be up 
     - ashudb  # service name 
    ports: # port forwarding 
      - 1177:8080 