apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: emppod
  name: emppod # name of pod 
  namespace: ashu-space  # namespace info 
spec: # is designed for application purpose 
  volumes: # to create volumes 
  - name: ashuvol1 # name of volume 
    emptyDir: {} # type of volume emptyDir vol can take storge from Minion random loc
  containers: # to create container 
  - image: nginx 
    name: ashuc1 
    volumeMounts:
    - name: ashuvol1
      mountPath: /usr/share/nginx/html/
      readOnly: true 
  - image: alpine
    name: emppod
    volumeMounts: # to mount the same volume 
    - name: ashuvol1 
      mountPath: /mnt/cisco # under container this loc will be created
    command: ["sh","-c","while true;do date >>/mnt/cisco/time.txt;sleep 5;done"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
