apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: privatepod
  name: privatepod
spec:
  imagePullSecrets: # calling secret 
  - name: ashuimgsec # name of secret 
  containers:
  - command:
    - ping
    - fb.com
    image: phx.ocir.io/axmbtg8judkl/cisco:v1 # OCR  based image 
    name: privatepod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
